version: '3.8'
services:
  biance-wss-connection:
    build: 
      context: .
      args:
        - HTTP_PROXY=
        - HTTPS_PROXY=
    container_name: biance-wss-connection
    volumes:
      - .:/app:cached
      - /app/__pycache__
      - /app/.pytest_cache
      - /app/logs
      - /app/json
    environment:
      - TZ=Asia/Shanghai
      - ENV=dev
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    shm_size: '0.5gb'
    restart: "no"
    command: python -m watchdog.watchmedo auto-restart --directory=/app --pattern=*.py --recursive -- python main.py